INSERT INTO yoga_classes (
  id,
  title,
  style,
  instructor,
  date_label,
  start_time,
  end_time,
  duration,
  level,
  energy,
  spots_left,
  price_label,
  description,
  studio_room,
  focus_tags,
  featured
)
VALUES
  (
    'sunrise-vinyasa',
    'Sunrise Vinyasa Flow',
    'Vinyasa',
    'Mira Joshi',
    'Today',
    '6:15 AM',
    '7:15 AM',
    '60 min',
    'All Levels',
    'Awakening',
    4,
    'Included in membership',
    'A steady morning sequence designed to open the hips, wake up the spine, and set an intentional rhythm for the day.',
    'Lotus Hall',
    ARRAY['Breathwork', 'Mobility', 'Focus'],
    TRUE
  ),
  (
    'midday-reset',
    'Midday Reset',
    'Restorative',
    'Rhea Menon',
    'Today',
    '1:00 PM',
    '1:45 PM',
    '45 min',
    'Beginner Friendly',
    'Calming',
    9,
    'Rs. 699 drop-in',
    'A low-impact reset featuring supported postures, deep breathing, and gentle release work to soften tension.',
    'Tulsi Studio',
    ARRAY['Recovery', 'Nervous System', 'Stillness'],
    FALSE
  ),
  (
    'power-core',
    'Power Core Strength',
    'Power Yoga',
    'Kabir Patel',
    'Tomorrow',
    '7:30 AM',
    '8:30 AM',
    '60 min',
    'Intermediate',
    'Strong',
    2,
    'Included in membership',
    'Dynamic standing sequences and targeted core work for practitioners who want heat, balance, and stamina.',
    'Shanti Deck',
    ARRAY['Strength', 'Balance', 'Heat'],
    TRUE
  )
ON CONFLICT (id) DO NOTHING;

